trip_ids_1 = [
    'home',
    'back home',
    'home (return trip)',
    'home (returning from work)',
    'home (again)',
    'home (returning from trader joe\'s)',
    'home (returning from grocery store)',
    'home (returning from my walk)',
    'home (returning from my travels)',
    'home (returning from errands)',
    'home (returning home at the end of the day)',
    'home (returning from target)',
]

trip_ids_3 = [
    'work',
    'office',
    'the office',
    'xyz corporation (office)',
    'abc corporation',
    'office building',
    'smith & co.',
    'xyz corporation (my office)',
    'xyz corporation (work)',
    'abc company (office)',
    'the washington post',
    'johnson & associates',
    'abc corporation (work)',
    'work (abc company)',
    'google building',
    'work (abc corporation)',
    'abc corporation (office)',
    'xyz corporation',
    'abc company',
    '123 main st (another work location)',
    '123 main st (office building)',
    'work (sales office)',
    'abc company (work)',
    'wework (coworking space)',
    '555 main St (office building)',
    '101 california street',
    '555 california street',
    '555 main st (office building)',
    'abc corporation (my office)',
    'abc company (my office)',
    'abc company (my workplace)',
    '555 building',
    (
        'work (health diagnosing and treating practitioners '
        'and other technical occupations field)'
    ),
    '123 main st',
    '100 first street (office building)',
    'construction site',
    'johnson & johnson law firm',
    'workplace',
    'work (management occupations field)',
    'abc tower',
    'work (abc tech company)',
    'the hive',
]


trip_ids_4 = [
    'client meeting location',
    'meeting location',
    'client meeting at abc company',
    'abc company (client meeting location)',
    'clientmeetspace',
    'clientmeetinglocation',
    'client meeting location (a hotel)',
    'client meeting location (hotel)',
    'client metting',
    'clientmeet',
    'client meeting',
    'client meeting at abc corporation',
    'client\'s office',
    'xyz corporation (client meeting location)',
    '123 main st (client meeting location)',
    'client meeting location (abc corporation)',
    'client meeting location (off site)',
    'client meeting location (off-site)',
    'client meeting (off-site location)',
    'client meeting (xyz inc.)',
    'xyz company (client meeting)',
    'client meeting at xyz corporation',
    'client meeting (off-site location) - abc company',
    'google',
    'client meeting location (starbucks)',
    'client meeting location (abc company)',
    'john\'s office',
    '456 elm st (another client meeting location)',
    'client meeting (xyz corporation)',
    'client\'s office (xyz corporation)',
]

trip_ids_6 = [
    'union station',
]

trip_ids_7 = [
    'public transportation'
]

trip_ids_8 = [
    'school',
    'george mason university',
    'university campus',
    'university',
    'fairfax high school',
    'campus',
    'san francisco state university',
    'university of san francisco',
]

trip_ids_9 = [
    'daycare',
]

trip_ids_11 = [
    'grocery store',
    'the grocery store',
    'gas station',
    'giant food',
    'giant food store',
    'shell gas station',
    'whole foods',
    'whole foods market',
    'fairfax corner shopping center',
    'fairfax corner',
    'national mall',
    'the national mall',
    'bookstore',
    'macy\'s',
    'exxon',
    'retail store',
    'safeway',
    'convenience store',
    'trader joe\'s',
    'the mall',
    'gas station (exxon)',
    'target',
    'department store',
    'walmart supercenter',
    'grocery store (whole foods)',
    'giant grocery store',
    'grocery store ghi',
    'grocery store def',
    'grocery store b',
    '555 market street',
    'store',
    '7-eleven',
    'the gap',
    'nordstrom',
    'walmart',
    'chevron',
    'walgreens',
    'home depot',
    'grocery store y',
    'grocery store 2',
    'grocery store z',
    'safeway (grocery store)',
    '76 gas station',
    'grocery store abc',
    'best buy',
    'costco',
    'one market plaza',
    'market',
    'the fish market',
    'bistro 33'
]

trip_ids_12 = [
    'bank of america',
    'the franklin hotel',
    'the ritz-carlton, washington, d.c.',
]

trip_ids_13 = [
    'starbucks',
    'local coffee shop',
    'coffee shop',
    'restaurant',
    'panera bread',
    'chipotle',
    'chipotle mexican grill',
    'the daily grind',
    'olive garden',
    'restaurant (chipotle)',
    'p.f. chang\'s restaurant',
    'bistro 51',
    'the cheesecake factory',
    'the little beet table',
    'subway',
    'cafe italiano',
    'the capital grille',
    'the italian kitchen',
    'chick-fil-a',
    'the sandwich shop',
    'subway restaurant',
    'chop\'t',
    'café xyz',
    'cafe xyz',
    'café x',
    'cafe x',
    'café',
    'cafe',
    'fisherman\'s grotto',
    'peet\'s coffee',
    'pizza hut',
    'fisherman\'s wharf',
    'joe\'s diner',
    'lunch spot',
    'cheesecake factory',
    'panda express',
    'pho 24',
    'lunch venue',
    'the fish counter',
    'sushi hut',
    'lunch spot (restaurant) - pizza house',
    'lunch spot (subway)',
    'restaurant for lunch ',
    'the fish market restaurant',
    'restaurant for lunch',
    'sushi house',
    'chez panisse',
    'pf chang\'s',
    'barnes & noble',
    'lunch',
    'chili\'s',
    'pancho\'s mexican restaurant',
    'zuni cafe',
    'joe\'s restaurant',
    'bistro 39',
    'p.f. chang\'s china bistro',
    'taco bell',
    'book passage',
    'p.f. chang\'s',
    'the sandwich board',
    'sushi express',
    'el farolito',
]

trip_ids_14 = [
    'library',
    'the library of congress',
    'library of congress',
    'fairfax library',
    'fedex',
    'post office',
    'fairfax public library',
    'fairfax city library',
    'martin luther king jr. memorial library',
    'library def',
    'san francisco public library',
    'library b',
    'the library',
    'san francisco city hall',
    'city hall',
    'the fish café',
    'lunch spot (joe\'s finer)'
]

trip_ids_15 = [
    'park',
    'the park',
    'local park',
    'dupont circle park',
    'dupont circle',
    'fairfax corner park',
    'fairfax corner ii',
    'rock creek park',
    'the white house',
    'the smithsonian',
    'lincoln park',
    'the lincoln memorial',
    'fairfax park',
    'smithsonian museum',
    'golden gate park',
    'park abc',
    'park a',
    'union square',
    'the golden gate bridge',
    'washington square park',
    'park (for a walk) - golden gate park',
    'public park',
    'movie theater',
    'central park',
    'amc theatres',
    'park (golden gate park)',
    'yerba buena park',
]

trip_ids_16 = [
    'gym',
    'fitness frenzy',
    '24 hour fitness',
    'the gym',
    'fitness studio',
    'fitness center',
]

trip_ids_17 = [
    'friend\'s house',
]

trip_ids_18 = [
    'hospital',
    'clinic',
    'doctor\'s office',
    'kaiser permanente medical center',
    'st. luke\'s hospital'
]

trip_ids_19 = [
    'community center',
]
